WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/manage.py changed, reloading.
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/web/settings/settings.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py changed, reloading.
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /api/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
           ^
TypeError: 'OrderList' object is not iterable
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /api/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
           ^
TypeError: 'OrderList' object is not iterable
ERROR:django.request:Internal Server Error: /api/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
           ^
TypeError: 'OrderList' object is not iterable
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/urls.py changed, reloading.
WARNING:django.request:Not Found: /api/
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py changed, reloading.
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /api/
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /api/street/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/request.py", line 416, in __getattr__
    return getattr(self._request, attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'keys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py", line 17, in get_queryset
    print(self.request.keys)
          ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/request.py", line 418, in __getattr__
    return self.__getattribute__(attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Request' object has no attribute 'keys'
ERROR:django.request:Internal Server Error: /api/street/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/request.py", line 416, in __getattr__
    return getattr(self._request, attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'keys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py", line 17, in get_queryset
    print(self.request.get.keys)
          ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/request.py", line 418, in __getattr__
    return self.__getattribute__(attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Request' object has no attribute 'keys'
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /api/street/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/request.py", line 416, in __getattr__
    return getattr(self._request, attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py", line 17, in get_queryset
    print(self.request.get.keys)
          ^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/request.py", line 418, in __getattr__
    return self.__getattribute__(attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Request' object has no attribute 'get'
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /api/street/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py", line 17, in get_queryset
    print(self.request.GET('g'))
          ^^^^^^^^^^^^^^^^^^^^^
TypeError: 'QueryDict' object is not callable
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /api/street/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py", line 16, in get_queryset
    queryset = StreerTbilisi.objects.filter(name_street__istartswith=self.request.GET.get('street'))[0:15]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/db/models/sql/query.py", line 1498, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/db/models/sql/query.py", line 1529, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/db/models/sql/query.py", line 1444, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/db/models/sql/query.py", line 1276, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
ERROR:django.request:Internal Server Error: /api/street/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py", line 16, in get_queryset
    queryset = StreerTbilisi.objects.filter(name_street__istartswith=self.request.GET.get('street'))[0:15]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/db/models/sql/query.py", line 1498, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/db/models/sql/query.py", line 1529, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/db/models/sql/query.py", line 1444, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-xbYPzM3q/lib64/python3.11/site-packages/django/db/models/sql/query.py", line 1276, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/tasks.py changed, reloading.
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/api/urls.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/models.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/models.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/models.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/models.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/models.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/models.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/models.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/models.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/models.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/models.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/models.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/models.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/models.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/models.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/models.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/models.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/models.py changed, reloading.
