07/Jan/2024 16:05:15   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
07/Jan/2024 16:05:17   INFO  Watching for file changes with StatReloader  None
07/Jan/2024 16:05:18   ERROR  Internal Server Error: /ordersearch/  (<class 'AttributeError'>, AttributeError("'OrderSearchForm' object has no attribute 'filterset'"), <traceback object at 0x7f33d741dec0>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 274, in get_context_data
    context['filterset'] = self.filterset
                           ^^^^^^^^^^^^^^
AttributeError: 'OrderSearchForm' object has no attribute 'filterset'
ERROR:django.request:Internal Server Error: /ordersearch/
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 274, in get_context_data
    context['filterset'] = self.filterset
                           ^^^^^^^^^^^^^^
AttributeError: 'OrderSearchForm' object has no attribute 'filterset'
07/Jan/2024 16:05:18   ERROR  "GET /ordersearch/ HTTP/1.1" 500 97551  None
ERROR:django.server:"GET /ordersearch/ HTTP/1.1" 500 97551
07/Jan/2024 16:05:42   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
07/Jan/2024 16:05:43   INFO  Watching for file changes with StatReloader  None
07/Jan/2024 16:05:44   ERROR  Internal Server Error: /ordersearch/  (<class 'AttributeError'>, AttributeError("'OrderSearchForm' object has no attribute 'filterset'"), <traceback object at 0x7f347e01b300>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 274, in get_context_data
    context['filterset'] = self.filterset
                           ^^^^^^^^^^^^^^
AttributeError: 'OrderSearchForm' object has no attribute 'filterset'
ERROR:django.request:Internal Server Error: /ordersearch/
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 274, in get_context_data
    context['filterset'] = self.filterset
                           ^^^^^^^^^^^^^^
AttributeError: 'OrderSearchForm' object has no attribute 'filterset'
07/Jan/2024 16:05:44   ERROR  "GET /ordersearch/ HTTP/1.1" 500 97572  None
ERROR:django.server:"GET /ordersearch/ HTTP/1.1" 500 97572
07/Jan/2024 16:05:46   ERROR  Internal Server Error: /ordersearch/  (<class 'AttributeError'>, AttributeError("'OrderSearchForm' object has no attribute 'filterset'"), <traceback object at 0x7f347ccabb80>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 274, in get_context_data
    context['filterset'] = self.filterset
                           ^^^^^^^^^^^^^^
AttributeError: 'OrderSearchForm' object has no attribute 'filterset'
ERROR:django.request:Internal Server Error: /ordersearch/
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 274, in get_context_data
    context['filterset'] = self.filterset
                           ^^^^^^^^^^^^^^
AttributeError: 'OrderSearchForm' object has no attribute 'filterset'
07/Jan/2024 16:05:46   ERROR  "GET /ordersearch/ HTTP/1.1" 500 97570  None
ERROR:django.server:"GET /ordersearch/ HTTP/1.1" 500 97570
07/Jan/2024 16:05:46   ERROR  Internal Server Error: /ordersearch/  (<class 'AttributeError'>, AttributeError("'OrderSearchForm' object has no attribute 'filterset'"), <traceback object at 0x7f347ccff9c0>)
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 274, in get_context_data
    context['filterset'] = self.filterset
                           ^^^^^^^^^^^^^^
AttributeError: 'OrderSearchForm' object has no attribute 'filterset'
ERROR:django.request:Internal Server Error: /ordersearch/
Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 274, in get_context_data
    context['filterset'] = self.filterset
                           ^^^^^^^^^^^^^^
AttributeError: 'OrderSearchForm' object has no attribute 'filterset'
07/Jan/2024 16:05:46   ERROR  "GET /ordersearch/ HTTP/1.1" 500 97570  None
ERROR:django.server:"GET /ordersearch/ HTTP/1.1" 500 97570
07/Jan/2024 16:06:27   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
07/Jan/2024 16:06:28   INFO  Watching for file changes with StatReloader  None
07/Jan/2024 16:06:29   INFO  "GET /ordersearch/ HTTP/1.1" 200 534360  None
INFO:django.server:"GET /ordersearch/ HTTP/1.1" 200 534360
07/Jan/2024 16:06:29   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
07/Jan/2024 16:06:35   INFO  "GET /user/51 HTTP/1.1" 200 16064  None
INFO:django.server:"GET /user/51 HTTP/1.1" 200 16064
07/Jan/2024 16:06:35   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
07/Jan/2024 16:06:35   INFO  "GET /media/images/%D1%8F.jpeg HTTP/1.1" 200 521837  None
INFO:django.server:"GET /media/images/%D1%8F.jpeg HTTP/1.1" 200 521837
07/Jan/2024 16:06:38   INFO  "GET /list_order?work_status=END HTTP/1.1" 200 53766  None
INFO:django.server:"GET /list_order?work_status=END HTTP/1.1" 200 53766
07/Jan/2024 16:06:38   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 15:23:54.305509
WARNING:root:ОШИБКА:        Не найден ни один пользователь, соответствующий запросу
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 53, in get_object
    obj = queryset.get()
          ^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 108, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 55, in get_object
    raise Http404(
django.http.response.Http404: Не найден ни один пользователь, соответствующий запросу

WARNING:root:============================================================
08/Jan/2024 15:23:54   WARNING  Bad Request: /user/164511456454154  None
WARNING:django.request:Bad Request: /user/164511456454154
08/Jan/2024 15:23:59   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 15:24:06   INFO  "GET /list_order HTTP/1.1" 200 53816  None
INFO:django.server:"GET /list_order HTTP/1.1" 200 53816
08/Jan/2024 15:24:06   INFO  "GET /static/css/fonts.css HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/css/fonts.css HTTP/1.1" 304 0
08/Jan/2024 15:24:06   INFO  "GET /static/css/custom.css HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/css/custom.css HTTP/1.1" 304 0
08/Jan/2024 15:24:06   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 15:24:06   INFO  "GET /static/js/custom.js HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/js/custom.js HTTP/1.1" 304 0
08/Jan/2024 15:24:06   INFO  "GET /static/images/master-na-chas_1.jpg HTTP/1.1" 200 323239  None
INFO:django.server:"GET /static/images/master-na-chas_1.jpg HTTP/1.1" 200 323239
08/Jan/2024 15:24:06   WARNING  Not Found: /favicon.ico  None
WARNING:django.request:Not Found: /favicon.ico
08/Jan/2024 15:24:06   WARNING  "GET /favicon.ico HTTP/1.1" 404 16307  None
WARNING:django.server:"GET /favicon.ico HTTP/1.1" 404 16307
08/Jan/2024 15:24:08   INFO  "GET /list_order?work_status=RCV HTTP/1.1" 200 30211  None
INFO:django.server:"GET /list_order?work_status=RCV HTTP/1.1" 200 30211
08/Jan/2024 15:24:08   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 15:24:11   INFO  "GET /list_order/1134 HTTP/1.1" 200 24799  None
INFO:django.server:"GET /list_order/1134 HTTP/1.1" 200 24799
08/Jan/2024 15:24:11   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 15:24:17   INFO  "GET /serv?type_work=FT HTTP/1.1" 200 776  None
INFO:django.server:"GET /serv?type_work=FT HTTP/1.1" 200 776
08/Jan/2024 15:24:17   INFO  "GET /list_order/1134 HTTP/1.1" 200 24796  None
INFO:django.server:"GET /list_order/1134 HTTP/1.1" 200 24796
08/Jan/2024 15:24:17   INFO  "GET /__debug__/history_sidebar/?store_id=f702bdb4b4e147ec8945544e0b9f336d HTTP/1.1" 200 13377  None
INFO:django.server:"GET /__debug__/history_sidebar/?store_id=f702bdb4b4e147ec8945544e0b9f336d HTTP/1.1" 200 13377
08/Jan/2024 15:24:27   INFO  "POST /list_order/1134 HTTP/1.1" 200 160  None
INFO:django.server:"POST /list_order/1134 HTTP/1.1" 200 160
08/Jan/2024 15:24:27   INFO  "GET /__debug__/history_sidebar/?store_id=8724dd94129b4c3c97e3e608b4ccf901 HTTP/1.1" 200 13344  None
INFO:django.server:"GET /__debug__/history_sidebar/?store_id=8724dd94129b4c3c97e3e608b4ccf901 HTTP/1.1" 200 13344
08/Jan/2024 15:24:29   INFO  "GET /changestatus?order_pk=1134&work_status=END HTTP/1.1" 200 32  None
INFO:django.server:"GET /changestatus?order_pk=1134&work_status=END HTTP/1.1" 200 32
08/Jan/2024 15:24:29   INFO  "GET /__debug__/history_sidebar/?store_id=fbd5977838e54ac88300675886f6a0c4 HTTP/1.1" 200 13390  None
INFO:django.server:"GET /__debug__/history_sidebar/?store_id=fbd5977838e54ac88300675886f6a0c4 HTTP/1.1" 200 13390
08/Jan/2024 15:24:32   INFO  "GET /list_order?work_status=RCV HTTP/1.1" 200 27809  None
INFO:django.server:"GET /list_order?work_status=RCV HTTP/1.1" 200 27809
08/Jan/2024 15:24:32   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 15:24:38   INFO  "GET /list_order/1096 HTTP/1.1" 200 25178  None
INFO:django.server:"GET /list_order/1096 HTTP/1.1" 200 25178
08/Jan/2024 15:24:38   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 15:24:50   INFO  "GET /stat/ HTTP/1.1" 200 191899  None
INFO:django.server:"GET /stat/ HTTP/1.1" 200 191899
08/Jan/2024 15:24:50   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 15:24:57   INFO  "GET /user/51 HTTP/1.1" 200 16064  None
INFO:django.server:"GET /user/51 HTTP/1.1" 200 16064
08/Jan/2024 15:24:57   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 15:24:57   INFO  "GET /media/images/%D1%8F.jpeg HTTP/1.1" 200 521837  None
INFO:django.server:"GET /media/images/%D1%8F.jpeg HTTP/1.1" 200 521837
08/Jan/2024 15:25:00   INFO  "GET /list_order HTTP/1.1" 200 53814  None
INFO:django.server:"GET /list_order HTTP/1.1" 200 53814
08/Jan/2024 15:25:00   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 15:25:01   INFO  "GET / HTTP/1.1" 200 43209  None
INFO:django.server:"GET / HTTP/1.1" 200 43209
08/Jan/2024 15:25:01   INFO  "GET /static/images/whatsapp.png HTTP/1.1" 200 167171  None
INFO:django.server:"GET /static/images/whatsapp.png HTTP/1.1" 200 167171
08/Jan/2024 15:25:01   INFO  "GET /static/images/telegram.gif HTTP/1.1" 200 38309  None
INFO:django.server:"GET /static/images/telegram.gif HTTP/1.1" 200 38309
08/Jan/2024 15:25:01   INFO  "GET /static/images/instagram.png HTTP/1.1" 200 79716  None
INFO:django.server:"GET /static/images/instagram.png HTTP/1.1" 200 79716
08/Jan/2024 15:25:01   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 15:25:01   INFO  "GET /static/images/1.jpg HTTP/1.1" 200 68159  None
INFO:django.server:"GET /static/images/1.jpg HTTP/1.1" 200 68159
08/Jan/2024 15:25:01   INFO  "GET /static/images/2.jpg HTTP/1.1" 200 73588  None
INFO:django.server:"GET /static/images/2.jpg HTTP/1.1" 200 73588
08/Jan/2024 15:25:01   INFO  "GET /static/images/3.jpg HTTP/1.1" 200 64252  None
INFO:django.server:"GET /static/images/3.jpg HTTP/1.1" 200 64252
08/Jan/2024 15:25:01   INFO  "GET /static/images/o-mastere-na-chas.png HTTP/1.1" 200 149377  None
INFO:django.server:"GET /static/images/o-mastere-na-chas.png HTTP/1.1" 200 149377
08/Jan/2024 15:25:01   INFO  "GET /static/images/usluga-master-na-chas.jpg HTTP/1.1" 200 159701  None
INFO:django.server:"GET /static/images/usluga-master-na-chas.jpg HTTP/1.1" 200 159701
08/Jan/2024 15:25:01   INFO  "GET /media/images/muzg-na-chas.jpg HTTP/1.1" 200 323830  None
INFO:django.server:"GET /media/images/muzg-na-chas.jpg HTTP/1.1" 200 323830
08/Jan/2024 15:25:01   INFO  "GET /static/fonts/fa-brands-400.woff2 HTTP/1.1" 200 74768  None
INFO:django.server:"GET /static/fonts/fa-brands-400.woff2 HTTP/1.1" 200 74768
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 16:44:02.383208
WARNING:root:ОШИБКА:        Не найден ни один пользователь, соответствующий запросу
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 53, in get_object
    obj = queryset.get()
          ^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 108, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 55, in get_object
    raise Http404(
django.http.response.Http404: Не найден ни один пользователь, соответствующий запросу

WARNING:root:============================================================
08/Jan/2024 16:44:02   WARNING  Bad Request: /user/164511456454154  None
WARNING:django.request:Bad Request: /user/164511456454154
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 16:44:25.630292
WARNING:root:ОШИБКА:        Не найден ни один пользователь, соответствующий запросу
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 53, in get_object
    obj = queryset.get()
          ^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 108, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 55, in get_object
    raise Http404(
django.http.response.Http404: Не найден ни один пользователь, соответствующий запросу

WARNING:root:============================================================
08/Jan/2024 16:44:25   WARNING  Bad Request: /user/164511456454154  None
WARNING:django.request:Bad Request: /user/164511456454154
08/Jan/2024 17:18:34   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 17:18:50   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.
08/Jan/2024 17:18:52   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 17:18:55   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 17:19:00   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 17:19:07   INFO  "GET / HTTP/1.1" 200 43140  None
INFO:django.server:"GET / HTTP/1.1" 200 43140
08/Jan/2024 17:19:07   INFO  "GET /static/js/jquery-3.3.1.min.js HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/js/jquery-3.3.1.min.js HTTP/1.1" 304 0
08/Jan/2024 17:19:07   INFO  "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
08/Jan/2024 17:19:07   INFO  "GET /static/js/wow.min.js HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/js/wow.min.js HTTP/1.1" 304 0
08/Jan/2024 17:19:07   INFO  "GET /static/js/mdb.min.js HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/js/mdb.min.js HTTP/1.1" 304 0
08/Jan/2024 17:19:07   INFO  "GET /static/css/fonts.css HTTP/1.1" 200 68940  None
INFO:django.server:"GET /static/css/fonts.css HTTP/1.1" 200 68940
08/Jan/2024 17:19:07   INFO  "GET /static/css/custom.css HTTP/1.1" 200 11110  None
08/Jan/2024 17:19:07   INFO  "GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 12664  None
INFO:django.server:"GET /static/css/custom.css HTTP/1.1" 200 11110
INFO:django.server:"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 12664
08/Jan/2024 17:19:07   INFO  "GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/js/owl.carousel.min.js HTTP/1.1" 304 0
08/Jan/2024 17:19:07   INFO  "GET /static/js/typed.min.js HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/js/typed.min.js HTTP/1.1" 304 0
08/Jan/2024 17:19:07   INFO  "GET /static/css/mdb.min.css HTTP/1.1" 200 254562  None
INFO:django.server:"GET /static/css/mdb.min.css HTTP/1.1" 200 254562
08/Jan/2024 17:19:07   INFO  "GET /static/js/jquery.malihu.PageScroll2id.min.js HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/js/jquery.malihu.PageScroll2id.min.js HTTP/1.1" 304 0
08/Jan/2024 17:19:07   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 17:19:07   INFO  "GET /static/js/maskedinput.min.js HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/js/maskedinput.min.js HTTP/1.1" 304 0
08/Jan/2024 17:19:07   INFO  "GET /static/js/custom.js HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/js/custom.js HTTP/1.1" 304 0
08/Jan/2024 17:19:07   INFO  "GET /static/images/master-na-chas_1.jpg HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/images/master-na-chas_1.jpg HTTP/1.1" 304 0
08/Jan/2024 17:19:07   INFO  "GET /static/images/o-mastere-na-chas.png HTTP/1.1" 200 149377  None
INFO:django.server:"GET /static/images/o-mastere-na-chas.png HTTP/1.1" 200 149377
08/Jan/2024 17:19:07   INFO  "GET /static/images/usluga-master-na-chas.jpg HTTP/1.1" 200 159701  None
INFO:django.server:"GET /static/images/usluga-master-na-chas.jpg HTTP/1.1" 200 159701
08/Jan/2024 17:19:07   INFO  "GET /static/images/3.jpg HTTP/1.1" 200 64252  None
INFO:django.server:"GET /static/images/3.jpg HTTP/1.1" 200 64252
08/Jan/2024 17:19:07   INFO  "GET /media/images/muzg-na-chas.jpg HTTP/1.1" 200 323830  None
INFO:django.server:"GET /media/images/muzg-na-chas.jpg HTTP/1.1" 200 323830
08/Jan/2024 17:19:07   INFO  "GET /static/fonts/Roboto-Bold.woff2 HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/fonts/Roboto-Bold.woff2 HTTP/1.1" 304 0
08/Jan/2024 17:19:07   INFO  "GET /static/fonts/Roboto-Regular.woff2 HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/fonts/Roboto-Regular.woff2 HTTP/1.1" 304 0
08/Jan/2024 17:19:07   INFO  "GET /static/fonts/Roboto-Medium.woff2 HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/fonts/Roboto-Medium.woff2 HTTP/1.1" 304 0
08/Jan/2024 17:19:07   INFO  "GET /static/fonts/fa-brands-400.woff2 HTTP/1.1" 200 74768  None
INFO:django.server:"GET /static/fonts/fa-brands-400.woff2 HTTP/1.1" 200 74768
08/Jan/2024 17:19:07   INFO  "GET /static/fonts/fa-regular-400.woff2 HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/fonts/fa-regular-400.woff2 HTTP/1.1" 304 0
08/Jan/2024 17:19:07   INFO  "GET /static/fonts/fa-solid-900.woff2 HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/fonts/fa-solid-900.woff2 HTTP/1.1" 304 0
08/Jan/2024 17:19:07   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 17:19:07   INFO  "GET /static/fonts/Roboto-Bold.woff HTTP/1.1" 200 315  None
INFO:django.server:"GET /static/fonts/Roboto-Bold.woff HTTP/1.1" 200 315
08/Jan/2024 17:19:07   INFO  "GET /static/fonts/Roboto-Regular.ttf HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/fonts/Roboto-Regular.ttf HTTP/1.1" 304 0
08/Jan/2024 17:19:07   INFO  "GET /static/fonts/Roboto-Medium.woff HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/fonts/Roboto-Medium.woff HTTP/1.1" 304 0
08/Jan/2024 17:19:08   INFO  "GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
08/Jan/2024 17:19:08   INFO  "GET /static/fonts/Roboto-Medium.ttf HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/fonts/Roboto-Medium.ttf HTTP/1.1" 304 0
08/Jan/2024 17:19:09   INFO  "GET /login/ HTTP/1.1" 200 15093  None
INFO:django.server:"GET /login/ HTTP/1.1" 200 15093
08/Jan/2024 17:19:09   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 17:19:09   INFO  "GET /static/fonts/Roboto-Light.woff2 HTTP/1.1" 200 315  None
INFO:django.server:"GET /static/fonts/Roboto-Light.woff2 HTTP/1.1" 200 315
08/Jan/2024 17:19:09   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 17:19:09   INFO  "GET /static/fonts/Roboto-Light.woff HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/fonts/Roboto-Light.woff HTTP/1.1" 304 0
08/Jan/2024 17:19:09   INFO  "GET /static/fonts/Roboto-Light.ttf HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/fonts/Roboto-Light.ttf HTTP/1.1" 304 0
08/Jan/2024 17:19:11   INFO  "POST /login/ HTTP/1.1" 302 0  None
INFO:django.server:"POST /login/ HTTP/1.1" 302 0
08/Jan/2024 17:19:11   INFO  "GET /list_order?work_status=RCV HTTP/1.1" 200 27809  None
INFO:django.server:"GET /list_order?work_status=RCV HTTP/1.1" 200 27809
08/Jan/2024 17:19:11   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 17:19:11   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 17:19:15   INFO  "GET /user/51 HTTP/1.1" 200 16064  None
INFO:django.server:"GET /user/51 HTTP/1.1" 200 16064
08/Jan/2024 17:19:15   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 17:19:15   INFO  "GET /media/images/%D1%8F.jpeg HTTP/1.1" 200 521837  None
INFO:django.server:"GET /media/images/%D1%8F.jpeg HTTP/1.1" 200 521837
08/Jan/2024 17:19:15   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 17:21:03   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.
08/Jan/2024 17:21:06   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 17:21:19   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
08/Jan/2024 17:21:21   INFO  Watching for file changes with StatReloader  None
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 17:21:24.264697
WARNING:root:ОШИБКА:        QuerySet.first() missing 1 required positional argument: 'self'
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 45, in get_context_data
    print(type(context['count']).first())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: QuerySet.first() missing 1 required positional argument: 'self'

WARNING:root:============================================================
08/Jan/2024 17:21:24   WARNING  Bad Request: /user/51  None
WARNING:django.request:Bad Request: /user/51
08/Jan/2024 17:21:24   WARNING  "GET /user/51 HTTP/1.1" 400 120  None
WARNING:django.server:"GET /user/51 HTTP/1.1" 400 120
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 17:21:44.494443
WARNING:root:ОШИБКА:        QuerySet.first() missing 1 required positional argument: 'self'
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 45, in get_context_data
    print(type(context['count']).first())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: QuerySet.first() missing 1 required positional argument: 'self'

WARNING:root:============================================================
08/Jan/2024 17:21:44   WARNING  Bad Request: /user/51  None
WARNING:django.request:Bad Request: /user/51
08/Jan/2024 17:21:44   WARNING  "GET /user/51 HTTP/1.1" 400 120  None
WARNING:django.server:"GET /user/51 HTTP/1.1" 400 120
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 17:21:46.529654
WARNING:root:ОШИБКА:        QuerySet.first() missing 1 required positional argument: 'self'
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 45, in get_context_data
    print(type(context['count']).first())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: QuerySet.first() missing 1 required positional argument: 'self'

WARNING:root:============================================================
08/Jan/2024 17:21:46   WARNING  Bad Request: /user/51  None
WARNING:django.request:Bad Request: /user/51
08/Jan/2024 17:21:46   WARNING  "GET /user/51 HTTP/1.1" 400 120  None
WARNING:django.server:"GET /user/51 HTTP/1.1" 400 120
08/Jan/2024 17:22:10   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
08/Jan/2024 17:22:12   INFO  Watching for file changes with StatReloader  None
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 17:22:13.715434
WARNING:root:ОШИБКА:        Cannot use QuerySet.first() on an unordered queryset performing aggregation. Add an ordering with order_by().
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 44, in get_context_data
    .filter(repairer_id=self.request.user).first()
                                           ^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/db/models/query.py", line 1055, in first
    self._check_ordering_first_last_queryset_aggregation(method="first")
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/db/models/query.py", line 1973, in _check_ordering_first_last_queryset_aggregation
    raise TypeError(
TypeError: Cannot use QuerySet.first() on an unordered queryset performing aggregation. Add an ordering with order_by().

WARNING:root:============================================================
08/Jan/2024 17:22:13   WARNING  Bad Request: /user/51  None
WARNING:django.request:Bad Request: /user/51
08/Jan/2024 17:22:13   WARNING  "GET /user/51 HTTP/1.1" 400 166  None
WARNING:django.server:"GET /user/51 HTTP/1.1" 400 166
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 17:22:34.620132
WARNING:root:ОШИБКА:        Cannot use QuerySet.first() on an unordered queryset performing aggregation. Add an ordering with order_by().
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 44, in get_context_data
    .filter(repairer_id=self.request.user).first()
                                           ^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/db/models/query.py", line 1055, in first
    self._check_ordering_first_last_queryset_aggregation(method="first")
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/db/models/query.py", line 1973, in _check_ordering_first_last_queryset_aggregation
    raise TypeError(
TypeError: Cannot use QuerySet.first() on an unordered queryset performing aggregation. Add an ordering with order_by().

WARNING:root:============================================================
08/Jan/2024 17:22:34   WARNING  Bad Request: /user/51  None
WARNING:django.request:Bad Request: /user/51
08/Jan/2024 17:22:34   WARNING  "GET /user/51 HTTP/1.1" 400 166  None
WARNING:django.server:"GET /user/51 HTTP/1.1" 400 166
08/Jan/2024 17:22:44   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
08/Jan/2024 17:22:45   INFO  Watching for file changes with StatReloader  None
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 17:22:46.736620
WARNING:root:ОШИБКА:        Cannot use QuerySet.first() on an unordered queryset performing aggregation. Add an ordering with order_by().
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 44, in get_context_data
    .filter(repairer_id=self.request.user).first()
                                           ^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/db/models/query.py", line 1055, in first
    self._check_ordering_first_last_queryset_aggregation(method="first")
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/db/models/query.py", line 1973, in _check_ordering_first_last_queryset_aggregation
    raise TypeError(
TypeError: Cannot use QuerySet.first() on an unordered queryset performing aggregation. Add an ordering with order_by().

WARNING:root:============================================================
08/Jan/2024 17:22:46   WARNING  Bad Request: /user/51  None
WARNING:django.request:Bad Request: /user/51
08/Jan/2024 17:22:46   WARNING  "GET /user/51 HTTP/1.1" 400 166  None
WARNING:django.server:"GET /user/51 HTTP/1.1" 400 166
08/Jan/2024 17:22:53   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
08/Jan/2024 17:22:54   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 17:22:55   INFO  "GET /user/51 HTTP/1.1" 200 16135  None
INFO:django.server:"GET /user/51 HTTP/1.1" 200 16135
08/Jan/2024 17:22:55   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 17:22:55   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 17:23:24   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
08/Jan/2024 17:23:26   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 17:23:38   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
08/Jan/2024 17:23:39   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 17:23:54   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
08/Jan/2024 17:23:55   INFO  Watching for file changes with StatReloader  None
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 17:23:58.976370
WARNING:root:ОШИБКА:        Cannot use QuerySet.first() on an unordered queryset performing aggregation. Add an ordering with order_by().
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 45, in get_context_data
    print(context['count'].first()[1])
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/db/models/query.py", line 1055, in first
    self._check_ordering_first_last_queryset_aggregation(method="first")
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/db/models/query.py", line 1973, in _check_ordering_first_last_queryset_aggregation
    raise TypeError(
TypeError: Cannot use QuerySet.first() on an unordered queryset performing aggregation. Add an ordering with order_by().

WARNING:root:============================================================
08/Jan/2024 17:23:59   WARNING  Bad Request: /user/51  None
WARNING:django.request:Bad Request: /user/51
08/Jan/2024 17:23:59   WARNING  "GET /user/51 HTTP/1.1" 400 166  None
WARNING:django.server:"GET /user/51 HTTP/1.1" 400 166
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 17:24:01.006309
WARNING:root:ОШИБКА:        Cannot use QuerySet.first() on an unordered queryset performing aggregation. Add an ordering with order_by().
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 45, in get_context_data
    print(context['count'].first()[1])
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/db/models/query.py", line 1055, in first
    self._check_ordering_first_last_queryset_aggregation(method="first")
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/db/models/query.py", line 1973, in _check_ordering_first_last_queryset_aggregation
    raise TypeError(
TypeError: Cannot use QuerySet.first() on an unordered queryset performing aggregation. Add an ordering with order_by().

WARNING:root:============================================================
08/Jan/2024 17:24:01   WARNING  Bad Request: /user/51  None
WARNING:django.request:Bad Request: /user/51
08/Jan/2024 17:24:01   WARNING  "GET /user/51 HTTP/1.1" 400 166  None
WARNING:django.server:"GET /user/51 HTTP/1.1" 400 166
08/Jan/2024 17:24:26   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
08/Jan/2024 17:24:27   INFO  Watching for file changes with StatReloader  None
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 17:24:28.131712
WARNING:root:ОШИБКА:        Cannot use QuerySet.first() on an unordered queryset performing aggregation. Add an ordering with order_by().
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 45, in get_context_data
    print(context['count'].first().count)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/db/models/query.py", line 1055, in first
    self._check_ordering_first_last_queryset_aggregation(method="first")
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/db/models/query.py", line 1973, in _check_ordering_first_last_queryset_aggregation
    raise TypeError(
TypeError: Cannot use QuerySet.first() on an unordered queryset performing aggregation. Add an ordering with order_by().

WARNING:root:============================================================
08/Jan/2024 17:24:28   WARNING  Bad Request: /user/51  None
WARNING:django.request:Bad Request: /user/51
08/Jan/2024 17:24:28   WARNING  "GET /user/51 HTTP/1.1" 400 166  None
WARNING:django.server:"GET /user/51 HTTP/1.1" 400 166
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 17:24:29.968106
WARNING:root:ОШИБКА:        Cannot use QuerySet.first() on an unordered queryset performing aggregation. Add an ordering with order_by().
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 45, in get_context_data
    print(context['count'].first().count)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/db/models/query.py", line 1055, in first
    self._check_ordering_first_last_queryset_aggregation(method="first")
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/db/models/query.py", line 1973, in _check_ordering_first_last_queryset_aggregation
    raise TypeError(
TypeError: Cannot use QuerySet.first() on an unordered queryset performing aggregation. Add an ordering with order_by().

WARNING:root:============================================================
08/Jan/2024 17:24:29   WARNING  Bad Request: /user/51  None
WARNING:django.request:Bad Request: /user/51
08/Jan/2024 17:24:29   WARNING  "GET /user/51 HTTP/1.1" 400 166  None
WARNING:django.server:"GET /user/51 HTTP/1.1" 400 166
08/Jan/2024 17:24:55   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
08/Jan/2024 17:24:57   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 17:24:59   INFO  "GET /user/51 HTTP/1.1" 200 16135  None
INFO:django.server:"GET /user/51 HTTP/1.1" 200 16135
08/Jan/2024 17:24:59   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 17:24:59   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 17:25:22   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
08/Jan/2024 17:25:23   INFO  Watching for file changes with StatReloader  None
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 17:25:25.084761
WARNING:root:ОШИБКА:        'dict' object has no attribute 'count'
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 45, in get_context_data
    print(context['count'][0].count)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'count'

WARNING:root:============================================================
08/Jan/2024 17:25:25   WARNING  Bad Request: /user/51  None
WARNING:django.request:Bad Request: /user/51
08/Jan/2024 17:25:25   WARNING  "GET /user/51 HTTP/1.1" 400 95  None
WARNING:django.server:"GET /user/51 HTTP/1.1" 400 95
08/Jan/2024 17:25:35   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
08/Jan/2024 17:25:36   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 17:25:38   INFO  "GET /user/51 HTTP/1.1" 200 16135  None
INFO:django.server:"GET /user/51 HTTP/1.1" 200 16135
08/Jan/2024 17:25:38   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 17:25:38   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 17:25:53   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
08/Jan/2024 17:25:54   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 17:25:55   INFO  "GET /user/51 HTTP/1.1" 200 16135  None
INFO:django.server:"GET /user/51 HTTP/1.1" 200 16135
08/Jan/2024 17:25:55   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 17:25:55   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 17:26:12   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
08/Jan/2024 17:26:13   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 17:26:15   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
08/Jan/2024 17:26:16   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 17:26:20   INFO  "GET /user/51 HTTP/1.1" 200 16136  None
INFO:django.server:"GET /user/51 HTTP/1.1" 200 16136
08/Jan/2024 17:26:20   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 17:26:20   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 17:26:31   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
08/Jan/2024 17:26:33   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 17:28:19   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
08/Jan/2024 17:28:20   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 17:29:42   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
08/Jan/2024 17:29:44   INFO  Watching for file changes with StatReloader  None
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 17:29:45.960797
WARNING:root:ОШИБКА:        name 'user' is not defined
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 41, in get_context_data
    context['count'] = DataFromOrderList.get_number_of_orders_from_OrderList(repairer_id=self.request.user)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py", line 21, in get_number_of_orders_from_OrderList
    .filter(repairer_id=user)[0]['count']
                        ^^^^
NameError: name 'user' is not defined

WARNING:root:============================================================
08/Jan/2024 17:29:46   WARNING  Bad Request: /user/51  None
WARNING:django.request:Bad Request: /user/51
08/Jan/2024 17:29:46   WARNING  "GET /user/51 HTTP/1.1" 400 83  None
WARNING:django.server:"GET /user/51 HTTP/1.1" 400 83
08/Jan/2024 17:31:21   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.
08/Jan/2024 17:31:23   INFO  Watching for file changes with StatReloader  None
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 17:31:24.631048
WARNING:root:ОШИБКА:        DataFromRepairerList.get_object_from_RepairerList() got an unexpected keyword argument 'user'
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 39, in get_context_data
    context['profile'] = DataFromRepairerList.get_object_from_RepairerList(user=self.object)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DataFromRepairerList.get_object_from_RepairerList() got an unexpected keyword argument 'user'

WARNING:root:============================================================
08/Jan/2024 17:31:24   WARNING  Bad Request: /user/51  None
WARNING:django.request:Bad Request: /user/51
08/Jan/2024 17:31:24   WARNING  "GET /user/51 HTTP/1.1" 400 150  None
WARNING:django.server:"GET /user/51 HTTP/1.1" 400 150
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 17:31:26.027149
WARNING:root:ОШИБКА:        DataFromRepairerList.get_object_from_RepairerList() got an unexpected keyword argument 'user'
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 39, in get_context_data
    context['profile'] = DataFromRepairerList.get_object_from_RepairerList(user=self.object)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DataFromRepairerList.get_object_from_RepairerList() got an unexpected keyword argument 'user'

WARNING:root:============================================================
08/Jan/2024 17:31:26   WARNING  Bad Request: /user/51  None
WARNING:django.request:Bad Request: /user/51
08/Jan/2024 17:31:26   WARNING  "GET /user/51 HTTP/1.1" 400 150  None
WARNING:django.server:"GET /user/51 HTTP/1.1" 400 150
08/Jan/2024 17:32:05   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
08/Jan/2024 17:32:07   INFO  Watching for file changes with StatReloader  None
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 17:32:07.813407
WARNING:root:ОШИБКА:        DataFromOrderList.get_number_of_orders_from_OrderList() got an unexpected keyword argument 'repairer_obj'
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 41, in get_context_data
    context['count'] = DataFromOrderList.get_number_of_orders_from_OrderList(repairer_obj=self.request.user)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DataFromOrderList.get_number_of_orders_from_OrderList() got an unexpected keyword argument 'repairer_obj'

WARNING:root:============================================================
08/Jan/2024 17:32:07   WARNING  Bad Request: /user/51  None
WARNING:django.request:Bad Request: /user/51
08/Jan/2024 17:32:07   WARNING  "GET /user/51 HTTP/1.1" 400 162  None
WARNING:django.server:"GET /user/51 HTTP/1.1" 400 162
08/Jan/2024 17:33:14   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.
08/Jan/2024 17:33:16   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 17:33:17   INFO  "GET /user/51 HTTP/1.1" 200 16066  None
INFO:django.server:"GET /user/51 HTTP/1.1" 200 16066
08/Jan/2024 17:33:17   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 17:33:17   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 17:34:34   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.
08/Jan/2024 17:34:35   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 17:35:27   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.
08/Jan/2024 17:35:28   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 17:38:27   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.
08/Jan/2024 17:38:29   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 17:39:27   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
08/Jan/2024 17:39:29   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 17:39:31   INFO  "GET /user/51 HTTP/1.1" 200 16066  None
INFO:django.server:"GET /user/51 HTTP/1.1" 200 16066
08/Jan/2024 17:39:31   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 17:39:31   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 17:40:18   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.
08/Jan/2024 17:40:19   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 17:40:20   INFO  "GET /user/51 HTTP/1.1" 200 16066  None
INFO:django.server:"GET /user/51 HTTP/1.1" 200 16066
08/Jan/2024 17:40:20   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 17:40:20   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 17:44:14   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.
08/Jan/2024 17:44:15   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 17:57:24   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.
08/Jan/2024 17:57:26   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 18:02:12   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
08/Jan/2024 18:02:13   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 18:02:15   INFO  "GET /user/51 HTTP/1.1" 200 16066  None
INFO:django.server:"GET /user/51 HTTP/1.1" 200 16066
08/Jan/2024 18:02:15   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:02:15   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:04:04   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
08/Jan/2024 18:04:06   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 18:12:47   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.
08/Jan/2024 18:12:49   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 18:12:53   INFO  "GET / HTTP/1.1" 200 43211  None
INFO:django.server:"GET / HTTP/1.1" 200 43211
08/Jan/2024 18:12:53   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:12:53   INFO  "GET /media/images/muzg-na-chas.jpg HTTP/1.1" 200 323830  None
INFO:django.server:"GET /media/images/muzg-na-chas.jpg HTTP/1.1" 200 323830
08/Jan/2024 18:12:53   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:12:55   INFO  "GET /list_order HTTP/1.1" 200 53814  None
INFO:django.server:"GET /list_order HTTP/1.1" 200 53814
08/Jan/2024 18:12:55   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:12:56   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:12:58   INFO  "GET / HTTP/1.1" 200 43209  None
INFO:django.server:"GET / HTTP/1.1" 200 43209
08/Jan/2024 18:12:58   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:12:58   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:13:06   INFO  "GET /street?street=j HTTP/1.1" 200 4  None
INFO:django.server:"GET /street?street=j HTTP/1.1" 200 4
08/Jan/2024 18:13:06   INFO  "GET /street?street=jv HTTP/1.1" 200 4  None
INFO:django.server:"GET /street?street=jv HTTP/1.1" 200 4
08/Jan/2024 18:13:06   INFO  "GET /__debug__/history_sidebar/?store_id=d152fdca055e403b88708af436d778a4 HTTP/1.1" 200 13351  None
INFO:django.server:"GET /__debug__/history_sidebar/?store_id=d152fdca055e403b88708af436d778a4 HTTP/1.1" 200 13351
08/Jan/2024 18:13:06   INFO  "GET /street?street=jvj HTTP/1.1" 200 4  None
INFO:django.server:"GET /street?street=jvj HTTP/1.1" 200 4
08/Jan/2024 18:13:06   INFO  "GET /street?street=jvjv HTTP/1.1" 200 4  None
INFO:django.server:"GET /street?street=jvjv HTTP/1.1" 200 4
08/Jan/2024 18:13:06   INFO  "GET /__debug__/history_sidebar/?store_id=7934f924a81d4447adede91553cd249c HTTP/1.1" 200 13353  None
INFO:django.server:"GET /__debug__/history_sidebar/?store_id=7934f924a81d4447adede91553cd249c HTTP/1.1" 200 13353
08/Jan/2024 18:13:09   INFO  "POST / HTTP/1.1" 200 203  None
INFO:django.server:"POST / HTTP/1.1" 200 203
08/Jan/2024 18:13:09   INFO  "GET /list_order/1136 HTTP/1.1" 200 24641  None
INFO:django.server:"GET /list_order/1136 HTTP/1.1" 200 24641
08/Jan/2024 18:13:09   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:13:09   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:13:14   INFO  "GET /list_order?work_status=RCV HTTP/1.1" 200 27809  None
INFO:django.server:"GET /list_order?work_status=RCV HTTP/1.1" 200 27809
08/Jan/2024 18:13:14   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:13:14   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:13:15   INFO  "GET /list_order?work_status=SND HTTP/1.1" 200 25345  None
INFO:django.server:"GET /list_order?work_status=SND HTTP/1.1" 200 25345
08/Jan/2024 18:13:15   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:13:15   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:13:23   INFO  "GET /invoice/delete-order/1136 HTTP/1.1" 200 14824  None
INFO:django.server:"GET /invoice/delete-order/1136 HTTP/1.1" 200 14824
08/Jan/2024 18:13:23   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:13:23   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:13:25   INFO  "POST /invoice/delete-order/1136 HTTP/1.1" 302 0  None
INFO:django.server:"POST /invoice/delete-order/1136 HTTP/1.1" 302 0
08/Jan/2024 18:13:25   INFO  "GET /list_order HTTP/1.1" 200 53814  None
INFO:django.server:"GET /list_order HTTP/1.1" 200 53814
08/Jan/2024 18:13:25   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:13:25   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:13:27   INFO  "GET /logout/ HTTP/1.1" 302 0  None
INFO:django.server:"GET /logout/ HTTP/1.1" 302 0
08/Jan/2024 18:13:27   INFO  "GET / HTTP/1.1" 200 43140  None
INFO:django.server:"GET / HTTP/1.1" 200 43140
08/Jan/2024 18:13:27   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:13:27   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:13:32   INFO  "GET /street?street=n HTTP/1.1" 200 4  None
INFO:django.server:"GET /street?street=n HTTP/1.1" 200 4
08/Jan/2024 18:13:32   INFO  "GET /street?street=n HTTP/1.1" 200 4  None
INFO:django.server:"GET /street?street=n HTTP/1.1" 200 4
08/Jan/2024 18:13:32   INFO  "GET /street?street=n%20n HTTP/1.1" 200 4  None
INFO:django.server:"GET /street?street=n%20n HTTP/1.1" 200 4
08/Jan/2024 18:13:33   INFO  "GET /__debug__/history_sidebar/?store_id=eaf472bae11a4ea7a3c22d59999556e6 HTTP/1.1" 200 13354  None
INFO:django.server:"GET /__debug__/history_sidebar/?store_id=eaf472bae11a4ea7a3c22d59999556e6 HTTP/1.1" 200 13354
08/Jan/2024 18:13:34   INFO  "POST / HTTP/1.1" 200 204  None
INFO:django.server:"POST / HTTP/1.1" 200 204
08/Jan/2024 18:13:34   INFO  "GET /__debug__/history_sidebar/?store_id=980e527621a541d98e0898cd9a3c0212 HTTP/1.1" 200 13329  None
INFO:django.server:"GET /__debug__/history_sidebar/?store_id=980e527621a541d98e0898cd9a3c0212 HTTP/1.1" 200 13329
08/Jan/2024 18:13:41   INFO  "GET / HTTP/1.1" 200 43140  None
INFO:django.server:"GET / HTTP/1.1" 200 43140
08/Jan/2024 18:13:41   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:13:41   INFO  "GET /media/images/muzg-na-chas.jpg HTTP/1.1" 200 323830  None
INFO:django.server:"GET /media/images/muzg-na-chas.jpg HTTP/1.1" 200 323830
08/Jan/2024 18:13:41   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:13:42   INFO  "GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 43  None
INFO:django.server:"GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 43
08/Jan/2024 18:13:44   INFO  "GET /admin/ HTTP/1.1" 302 0  None
INFO:django.server:"GET /admin/ HTTP/1.1" 302 0
08/Jan/2024 18:13:44   INFO  "GET /admin/login/?next=/admin/ HTTP/1.1" 200 14422  None
INFO:django.server:"GET /admin/login/?next=/admin/ HTTP/1.1" 200 14422
08/Jan/2024 18:13:45   INFO  "GET /static/admin/css/base.css HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/admin/css/base.css HTTP/1.1" 304 0
08/Jan/2024 18:13:45   INFO  "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
08/Jan/2024 18:13:45   INFO  "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
08/Jan/2024 18:13:45   INFO  "GET /static/admin/css/responsive.css HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
08/Jan/2024 18:13:45   INFO  "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
08/Jan/2024 18:13:45   INFO  "GET /static/admin/js/theme.js HTTP/1.1" 304 0  None
08/Jan/2024 18:13:45   INFO  "GET /static/admin/css/login.css HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO:django.server:"GET /static/admin/css/login.css HTTP/1.1" 304 0
08/Jan/2024 18:13:48   INFO  "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0  None
INFO:django.server:"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
08/Jan/2024 18:13:48   INFO  "GET /admin/ HTTP/1.1" 200 23475  None
INFO:django.server:"GET /admin/ HTTP/1.1" 200 23475
08/Jan/2024 18:13:48   INFO  "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
08/Jan/2024 18:13:48   INFO  "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331  None
INFO:django.server:"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
08/Jan/2024 18:13:48   INFO  "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380  None
INFO:django.server:"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
08/Jan/2024 18:13:57   INFO  "GET /admin/app_site/orderlist/ HTTP/1.1" 200 90612  None
INFO:django.server:"GET /admin/app_site/orderlist/ HTTP/1.1" 200 90612
08/Jan/2024 18:13:57   INFO  "GET /static/admin/img/search.svg HTTP/1.1" 200 458  None
INFO:django.server:"GET /static/admin/img/search.svg HTTP/1.1" 200 458
08/Jan/2024 18:13:57   INFO  "GET /static/admin/js/core.js HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/admin/js/core.js HTTP/1.1" 304 0
08/Jan/2024 18:13:57   INFO  "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0  None
08/Jan/2024 18:13:57   INFO  "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO:django.server:"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
08/Jan/2024 18:13:57   INFO  "GET /static/admin/css/changelists.css HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/admin/css/changelists.css HTTP/1.1" 304 0
08/Jan/2024 18:13:57   INFO  "GET /static/admin/js/actions.js HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/admin/js/actions.js HTTP/1.1" 304 0
08/Jan/2024 18:13:57   INFO  "GET /static/admin/js/filters.js HTTP/1.1" 200 978  None
INFO:django.server:"GET /static/admin/js/filters.js HTTP/1.1" 200 978
08/Jan/2024 18:13:57   INFO  "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
08/Jan/2024 18:13:57   INFO  "GET /static/admin/js/urlify.js HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/admin/js/urlify.js HTTP/1.1" 304 0
08/Jan/2024 18:13:57   INFO  "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
08/Jan/2024 18:13:57   INFO  "GET /admin/jsi18n/ HTTP/1.1" 200 16066  None
INFO:django.server:"GET /admin/jsi18n/ HTTP/1.1" 200 16066
08/Jan/2024 18:13:57   INFO  "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0  None
INFO:django.server:"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
08/Jan/2024 18:13:57   INFO  "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331  None
INFO:django.server:"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
08/Jan/2024 18:14:03   INFO  "GET /admin/app_site/invoice/ HTTP/1.1" 200 82351  None
INFO:django.server:"GET /admin/app_site/invoice/ HTTP/1.1" 200 82351
08/Jan/2024 18:14:03   INFO  "GET /admin/jsi18n/ HTTP/1.1" 200 16066  None
INFO:django.server:"GET /admin/jsi18n/ HTTP/1.1" 200 16066
08/Jan/2024 18:14:05   INFO  "GET /admin/app_site/orderlist/ HTTP/1.1" 200 90612  None
INFO:django.server:"GET /admin/app_site/orderlist/ HTTP/1.1" 200 90612
08/Jan/2024 18:14:05   INFO  "GET /admin/jsi18n/ HTTP/1.1" 200 16066  None
INFO:django.server:"GET /admin/jsi18n/ HTTP/1.1" 200 16066
08/Jan/2024 18:14:55   INFO  "GET /login/ HTTP/1.1" 200 15221  None
INFO:django.server:"GET /login/ HTTP/1.1" 200 15221
08/Jan/2024 18:14:55   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:14:55   INFO  "GET /static/fonts/Roboto-Light.woff2 HTTP/1.1" 200 315  None
INFO:django.server:"GET /static/fonts/Roboto-Light.woff2 HTTP/1.1" 200 315
08/Jan/2024 18:14:55   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:14:58   INFO  "POST /login/ HTTP/1.1" 302 0  None
INFO:django.server:"POST /login/ HTTP/1.1" 302 0
08/Jan/2024 18:14:58   INFO  "GET /list_order?work_status=RCV HTTP/1.1" 200 27809  None
INFO:django.server:"GET /list_order?work_status=RCV HTTP/1.1" 200 27809
08/Jan/2024 18:14:58   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:14:58   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:14:59   INFO  "GET /list_order HTTP/1.1" 200 53814  None
INFO:django.server:"GET /list_order HTTP/1.1" 200 53814
08/Jan/2024 18:15:00   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:15:00   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:15:00   INFO  "GET /list_order?work_status=RCV HTTP/1.1" 200 27809  None
INFO:django.server:"GET /list_order?work_status=RCV HTTP/1.1" 200 27809
08/Jan/2024 18:15:00   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:15:01   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:15:01   INFO  "GET /list_order?work_status=END HTTP/1.1" 200 53881  None
INFO:django.server:"GET /list_order?work_status=END HTTP/1.1" 200 53881
08/Jan/2024 18:15:02   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:15:02   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:15:03   INFO  "GET /list_order?work_status=SND HTTP/1.1" 200 23097  None
INFO:django.server:"GET /list_order?work_status=SND HTTP/1.1" 200 23097
08/Jan/2024 18:15:03   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:15:03   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:15:04   INFO  "GET /list_order?work_status=RCV HTTP/1.1" 200 27809  None
INFO:django.server:"GET /list_order?work_status=RCV HTTP/1.1" 200 27809
08/Jan/2024 18:15:04   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:15:04   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:15:10   INFO  "GET /list_order?work_status=END HTTP/1.1" 200 53881  None
INFO:django.server:"GET /list_order?work_status=END HTTP/1.1" 200 53881
08/Jan/2024 18:15:10   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:15:10   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:16:44   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
08/Jan/2024 18:16:45   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 18:33:26   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
08/Jan/2024 18:33:27   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 18:33:32   INFO  "GET /list_order/1134 HTTP/1.1" 200 25145  None
INFO:django.server:"GET /list_order/1134 HTTP/1.1" 200 25145
08/Jan/2024 18:33:32   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:33:32   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:34:35   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
08/Jan/2024 18:34:36   INFO  Watching for file changes with StatReloader  None
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 18:48:56.416620
WARNING:root:ОШИБКА:        type object 'DataFromInvoice' has no attribute 'get_amount_money_of_orders_from_Invoice'
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 41, in get_context_data
    context['sum'] = DataFromInvoice.get_amount_money_of_orders_from_Invoice(repairer=self.request.user)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'DataFromInvoice' has no attribute 'get_amount_money_of_orders_from_Invoice'

WARNING:root:============================================================
08/Jan/2024 18:48:56   WARNING  Bad Request: /user/1  None
WARNING:django.request:Bad Request: /user/1
08/Jan/2024 18:50:27   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 18:50:33   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 18:50:44   INFO  Watching for file changes with StatReloader  None
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 18:50:49.484292
WARNING:root:ОШИБКА:        type object 'DataFromInvoice' has no attribute 'get_amount_money_of_orders_from_Invoice'
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 41, in get_context_data
    context['sum'] = DataFromInvoice.get_amount_money_of_orders_from_Invoice(repairer=self.request.user)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'DataFromInvoice' has no attribute 'get_amount_money_of_orders_from_Invoice'

WARNING:root:============================================================
08/Jan/2024 18:50:49   WARNING  Bad Request: /user/51  None
WARNING:django.request:Bad Request: /user/51
08/Jan/2024 18:50:49   WARNING  "GET /user/51 HTTP/1.1" 400 145  None
WARNING:django.server:"GET /user/51 HTTP/1.1" 400 145
08/Jan/2024 18:53:08   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.
08/Jan/2024 18:53:09   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 18:53:11   INFO  "GET /user/51 HTTP/1.1" 200 16164  None
INFO:django.server:"GET /user/51 HTTP/1.1" 200 16164
08/Jan/2024 18:53:11   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:53:11   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:53:11   INFO  "GET /media/images/%D1%8F.jpeg HTTP/1.1" 200 521837  None
INFO:django.server:"GET /media/images/%D1%8F.jpeg HTTP/1.1" 200 521837
08/Jan/2024 18:53:39   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.
08/Jan/2024 18:53:40   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 18:53:40   INFO  "GET /user/51 HTTP/1.1" 200 16066  None
INFO:django.server:"GET /user/51 HTTP/1.1" 200 16066
08/Jan/2024 18:53:40   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 18:53:40   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 18:53:52.366458
WARNING:root:ОШИБКА:        Не найден ни один пользователь, соответствующий запросу
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 53, in get_object
    obj = queryset.get()
          ^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 108, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 55, in get_object
    raise Http404(
django.http.response.Http404: Не найден ни один пользователь, соответствующий запросу

WARNING:root:============================================================
08/Jan/2024 18:53:52   WARNING  Bad Request: /user/164511456454154  None
WARNING:django.request:Bad Request: /user/164511456454154
08/Jan/2024 19:01:01   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 19:01:06   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 19:01:10   INFO  "GET /list_order?work_status=RCV HTTP/1.1" 200 27811  None
INFO:django.server:"GET /list_order?work_status=RCV HTTP/1.1" 200 27811
08/Jan/2024 19:01:11   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:01:11   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:01:14   INFO  "GET /list_order?work_status=END HTTP/1.1" 200 53881  None
INFO:django.server:"GET /list_order?work_status=END HTTP/1.1" 200 53881
08/Jan/2024 19:01:14   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:01:14   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 19:01:15.531832
WARNING:root:ОШИБКА:        'dict' object has no attribute 'pk'
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 119, in get_context_data
    context['next'] = DataFromOrderList.get_next_number_for_paginator_from_OrderList_(repairer= self.request.user, pk=self.object.pk)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py", line 33, in get_next_number_for_paginator_from_OrderList_
    return OrderList.objects.filter(pk__gt=pk, repairer_id=repairer).values('pk').first().pk
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'pk'

WARNING:root:============================================================
08/Jan/2024 19:01:15   WARNING  Bad Request: /list_order/1134  None
WARNING:django.request:Bad Request: /list_order/1134
08/Jan/2024 19:01:15   WARNING  "GET /list_order/1134 HTTP/1.1" 400 92  None
WARNING:django.server:"GET /list_order/1134 HTTP/1.1" 400 92
08/Jan/2024 19:02:39   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.
08/Jan/2024 19:02:40   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 19:02:42   INFO  "GET /list_order/1134 HTTP/1.1" 200 25145  None
INFO:django.server:"GET /list_order/1134 HTTP/1.1" 200 25145
08/Jan/2024 19:02:42   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:02:42   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:02:44   INFO  "GET /list_order/1133 HTTP/1.1" 200 25116  None
INFO:django.server:"GET /list_order/1133 HTTP/1.1" 200 25116
08/Jan/2024 19:02:44   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:02:45   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:02:46   INFO  "GET /list_order/1134 HTTP/1.1" 200 25143  None
INFO:django.server:"GET /list_order/1134 HTTP/1.1" 200 25143
08/Jan/2024 19:02:46   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:02:46   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:02:46   INFO  "GET /list_order/1135 HTTP/1.1" 200 24667  None
INFO:django.server:"GET /list_order/1135 HTTP/1.1" 200 24667
08/Jan/2024 19:02:46   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:02:46   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:02:48   INFO  "GET /list_order/1134 HTTP/1.1" 200 25143  None
INFO:django.server:"GET /list_order/1134 HTTP/1.1" 200 25143
08/Jan/2024 19:02:48   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:02:48   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:02:49   INFO  "GET /list_order/1133 HTTP/1.1" 200 25116  None
INFO:django.server:"GET /list_order/1133 HTTP/1.1" 200 25116
08/Jan/2024 19:02:49   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:02:49   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:03:29   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.
08/Jan/2024 19:03:31   INFO  Watching for file changes with StatReloader  None
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 19:03:31.880664
WARNING:root:ОШИБКА:        'dict' object has no attribute 'pk'
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 119, in get_context_data
    context['next'] = DataFromOrderList.get_next_number_for_paginator_from_OrderList_(repairer= self.request.user, pk=self.object.pk)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py", line 33, in get_next_number_for_paginator_from_OrderList_
    return OrderList.objects.filter(pk__gt=pk, repairer_id=repairer).values('pk').first().pk
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'pk'

WARNING:root:============================================================
08/Jan/2024 19:03:31   WARNING  Bad Request: /list_order/1133  None
WARNING:django.request:Bad Request: /list_order/1133
08/Jan/2024 19:03:31   WARNING  "GET /list_order/1133 HTTP/1.1" 400 92  None
WARNING:django.server:"GET /list_order/1133 HTTP/1.1" 400 92
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 19:03:47.426492
WARNING:root:ОШИБКА:        'dict' object has no attribute 'pk'
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 119, in get_context_data
    context['next'] = DataFromOrderList.get_next_number_for_paginator_from_OrderList_(repairer= self.request.user, pk=self.object.pk)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py", line 33, in get_next_number_for_paginator_from_OrderList_
    return OrderList.objects.filter(pk__gt=pk, repairer_id=repairer).values('pk').first().pk
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'pk'

WARNING:root:============================================================
08/Jan/2024 19:03:47   WARNING  Bad Request: /list_order/1133  None
WARNING:django.request:Bad Request: /list_order/1133
08/Jan/2024 19:03:47   WARNING  "GET /list_order/1133 HTTP/1.1" 400 92  None
WARNING:django.server:"GET /list_order/1133 HTTP/1.1" 400 92
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 19:03:48.310074
WARNING:root:ОШИБКА:        'dict' object has no attribute 'pk'
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 119, in get_context_data
    context['next'] = DataFromOrderList.get_next_number_for_paginator_from_OrderList_(repairer= self.request.user, pk=self.object.pk)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py", line 33, in get_next_number_for_paginator_from_OrderList_
    return OrderList.objects.filter(pk__gt=pk, repairer_id=repairer).values('pk').first().pk
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'pk'

WARNING:root:============================================================
08/Jan/2024 19:03:48   WARNING  Bad Request: /list_order/1133  None
WARNING:django.request:Bad Request: /list_order/1133
08/Jan/2024 19:03:48   WARNING  "GET /list_order/1133 HTTP/1.1" 400 92  None
WARNING:django.server:"GET /list_order/1133 HTTP/1.1" 400 92
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 19:03:58.990998
WARNING:root:ОШИБКА:        'dict' object has no attribute 'pk'
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 109, in get
    context = self.get_context_data(object=self.object)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 119, in get_context_data
    context['next'] = DataFromOrderList.get_next_number_for_paginator_from_OrderList_(repairer= self.request.user, pk=self.object.pk)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py", line 33, in get_next_number_for_paginator_from_OrderList_
    return OrderList.objects.filter(pk__gt=pk, repairer_id=repairer).values('pk').first().pk
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'pk'

WARNING:root:============================================================
08/Jan/2024 19:03:59   WARNING  Bad Request: /list_order/1133  None
WARNING:django.request:Bad Request: /list_order/1133
08/Jan/2024 19:03:59   WARNING  "GET /list_order/1133 HTTP/1.1" 400 92  None
WARNING:django.server:"GET /list_order/1133 HTTP/1.1" 400 92
08/Jan/2024 19:05:03   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.
08/Jan/2024 19:05:05   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 19:07:01   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
08/Jan/2024 19:07:02   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 19:07:06   INFO  "GET /list_order/1133 HTTP/1.1" 200 25118  None
INFO:django.server:"GET /list_order/1133 HTTP/1.1" 200 25118
08/Jan/2024 19:07:06   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:07:06   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:07:08   INFO  "GET /list_order/1132 HTTP/1.1" 200 25133  None
INFO:django.server:"GET /list_order/1132 HTTP/1.1" 200 25133
08/Jan/2024 19:07:08   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:07:08   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:07:09   INFO  "GET /list_order/1133 HTTP/1.1" 200 25116  None
INFO:django.server:"GET /list_order/1133 HTTP/1.1" 200 25116
08/Jan/2024 19:07:09   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:07:09   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:07:10   INFO  "GET /list_order/1134 HTTP/1.1" 200 25143  None
INFO:django.server:"GET /list_order/1134 HTTP/1.1" 200 25143
08/Jan/2024 19:07:10   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:07:10   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:07:10   INFO  "GET /list_order/1135 HTTP/1.1" 200 24667  None
INFO:django.server:"GET /list_order/1135 HTTP/1.1" 200 24667
08/Jan/2024 19:07:10   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:07:10   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:07:11   INFO  "GET /list_order/1134 HTTP/1.1" 200 25143  None
INFO:django.server:"GET /list_order/1134 HTTP/1.1" 200 25143
08/Jan/2024 19:07:11   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:07:11   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:07:12   INFO  "GET /list_order/1135 HTTP/1.1" 200 24667  None
INFO:django.server:"GET /list_order/1135 HTTP/1.1" 200 24667
08/Jan/2024 19:07:12   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:07:12   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:07:13   INFO  "GET /list_order/1134 HTTP/1.1" 200 25143  None
INFO:django.server:"GET /list_order/1134 HTTP/1.1" 200 25143
08/Jan/2024 19:07:13   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:07:13   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:07:14   INFO  "GET /list_order/1133 HTTP/1.1" 200 25116  None
INFO:django.server:"GET /list_order/1133 HTTP/1.1" 200 25116
08/Jan/2024 19:07:14   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:07:14   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 19:07:22.871075
WARNING:root:ОШИБКА:        Не найден ни один пользователь, соответствующий запросу
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 53, in get_object
    obj = queryset.get()
          ^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 108, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 55, in get_object
    raise Http404(
django.http.response.Http404: Не найден ни один пользователь, соответствующий запросу

WARNING:root:============================================================
08/Jan/2024 19:07:22   WARNING  Bad Request: /user/164511456454154  None
WARNING:django.request:Bad Request: /user/164511456454154
08/Jan/2024 19:10:30   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
08/Jan/2024 19:10:32   INFO  Watching for file changes with StatReloader  None
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 19:10:40.220705
WARNING:root:ОШИБКА:        DataFromOrderList.get_data_from_OrderList_all_order_status() got an unexpected keyword argument 'repairer_id'
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 108, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/detail.py", line 31, in get_object
    queryset = self.get_queryset()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 122, in get_queryset
    return DataFromOrderList.get_data_from_OrderList_all_order_status(repairer_id=self.request.user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DataFromOrderList.get_data_from_OrderList_all_order_status() got an unexpected keyword argument 'repairer_id'

WARNING:root:============================================================
08/Jan/2024 19:10:40   WARNING  Bad Request: /list_order/1133  None
WARNING:django.request:Bad Request: /list_order/1133
08/Jan/2024 19:10:40   WARNING  "GET /list_order/1133 HTTP/1.1" 400 166  None
WARNING:django.server:"GET /list_order/1133 HTTP/1.1" 400 166
08/Jan/2024 19:11:01   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
08/Jan/2024 19:11:02   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 19:11:12   INFO  "GET /list_order/1133 HTTP/1.1" 200 25118  None
INFO:django.server:"GET /list_order/1133 HTTP/1.1" 200 25118
08/Jan/2024 19:11:12   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:12   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:14   INFO  "GET /list_order/1132 HTTP/1.1" 200 25133  None
INFO:django.server:"GET /list_order/1132 HTTP/1.1" 200 25133
08/Jan/2024 19:11:14   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:14   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:15   INFO  "GET /list_order/1131 HTTP/1.1" 200 25144  None
INFO:django.server:"GET /list_order/1131 HTTP/1.1" 200 25144
08/Jan/2024 19:11:15   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:15   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:16   INFO  "GET /list_order/1132 HTTP/1.1" 200 25133  None
INFO:django.server:"GET /list_order/1132 HTTP/1.1" 200 25133
08/Jan/2024 19:11:16   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:16   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:18   INFO  "GET /list_order/1132 HTTP/1.1" 200 25133  None
INFO:django.server:"GET /list_order/1132 HTTP/1.1" 200 25133
08/Jan/2024 19:11:18   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:18   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:20   INFO  "GET /list_order/1133 HTTP/1.1" 200 25116  None
INFO:django.server:"GET /list_order/1133 HTTP/1.1" 200 25116
08/Jan/2024 19:11:20   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:20   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:20   INFO  "GET /list_order/1134 HTTP/1.1" 200 25143  None
INFO:django.server:"GET /list_order/1134 HTTP/1.1" 200 25143
08/Jan/2024 19:11:20   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:21   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:21   INFO  "GET /list_order/1135 HTTP/1.1" 200 24667  None
INFO:django.server:"GET /list_order/1135 HTTP/1.1" 200 24667
08/Jan/2024 19:11:21   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:21   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:23   INFO  "GET /list_order/1134 HTTP/1.1" 200 25143  None
INFO:django.server:"GET /list_order/1134 HTTP/1.1" 200 25143
08/Jan/2024 19:11:23   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:23   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:25   INFO  "GET /list_order?work_status=RCV HTTP/1.1" 200 27809  None
INFO:django.server:"GET /list_order?work_status=RCV HTTP/1.1" 200 27809
08/Jan/2024 19:11:25   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:25   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:26   INFO  "GET /list_order?work_status=END HTTP/1.1" 200 53881  None
INFO:django.server:"GET /list_order?work_status=END HTTP/1.1" 200 53881
08/Jan/2024 19:11:26   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:26   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:28   INFO  "GET /list_order/1134 HTTP/1.1" 200 25143  None
INFO:django.server:"GET /list_order/1134 HTTP/1.1" 200 25143
08/Jan/2024 19:11:28   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:28   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:29   INFO  "GET /list_order/1135 HTTP/1.1" 200 24667  None
INFO:django.server:"GET /list_order/1135 HTTP/1.1" 200 24667
08/Jan/2024 19:11:29   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:29   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:33   INFO  "GET /list_order/1134 HTTP/1.1" 200 25143  None
INFO:django.server:"GET /list_order/1134 HTTP/1.1" 200 25143
08/Jan/2024 19:11:33   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:33   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:34   INFO  "GET /list_order/1133 HTTP/1.1" 200 25116  None
INFO:django.server:"GET /list_order/1133 HTTP/1.1" 200 25116
08/Jan/2024 19:11:35   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:35   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:35   INFO  "GET /list_order/1132 HTTP/1.1" 200 25133  None
INFO:django.server:"GET /list_order/1132 HTTP/1.1" 200 25133
08/Jan/2024 19:11:35   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:35   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:37   INFO  "GET /list_order/1131 HTTP/1.1" 200 25144  None
INFO:django.server:"GET /list_order/1131 HTTP/1.1" 200 25144
08/Jan/2024 19:11:37   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:37   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:38   INFO  "GET /list_order?work_status=RCV HTTP/1.1" 200 27809  None
INFO:django.server:"GET /list_order?work_status=RCV HTTP/1.1" 200 27809
08/Jan/2024 19:11:38   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:38   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:39   INFO  "GET /list_order?work_status=END HTTP/1.1" 200 53881  None
INFO:django.server:"GET /list_order?work_status=END HTTP/1.1" 200 53881
08/Jan/2024 19:11:39   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:39   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:46   INFO  "GET /list_order?work_status=RCV HTTP/1.1" 200 27809  None
INFO:django.server:"GET /list_order?work_status=RCV HTTP/1.1" 200 27809
08/Jan/2024 19:11:46   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:46   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:52   INFO  "GET /list_order/1135 HTTP/1.1" 200 24667  None
INFO:django.server:"GET /list_order/1135 HTTP/1.1" 200 24667
08/Jan/2024 19:11:52   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:52   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:54   INFO  "GET /list_order/1134 HTTP/1.1" 200 25143  None
INFO:django.server:"GET /list_order/1134 HTTP/1.1" 200 25143
08/Jan/2024 19:11:54   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:54   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:54   INFO  "GET /list_order/1133 HTTP/1.1" 200 25116  None
INFO:django.server:"GET /list_order/1133 HTTP/1.1" 200 25116
08/Jan/2024 19:11:55   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:55   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:55   INFO  "GET /list_order/1132 HTTP/1.1" 200 25133  None
INFO:django.server:"GET /list_order/1132 HTTP/1.1" 200 25133
08/Jan/2024 19:11:55   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:55   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:56   INFO  "GET /list_order/1131 HTTP/1.1" 200 25144  None
INFO:django.server:"GET /list_order/1131 HTTP/1.1" 200 25144
08/Jan/2024 19:11:56   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:56   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:56   INFO  "GET /list_order/1130 HTTP/1.1" 200 25101  None
INFO:django.server:"GET /list_order/1130 HTTP/1.1" 200 25101
08/Jan/2024 19:11:56   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:56   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:57   INFO  "GET /list_order/1129 HTTP/1.1" 200 25126  None
INFO:django.server:"GET /list_order/1129 HTTP/1.1" 200 25126
08/Jan/2024 19:11:57   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:57   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:57   INFO  "GET /list_order/1128 HTTP/1.1" 200 25092  None
INFO:django.server:"GET /list_order/1128 HTTP/1.1" 200 25092
08/Jan/2024 19:11:57   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:57   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:57   INFO  "GET /list_order/1126 HTTP/1.1" 200 25112  None
INFO:django.server:"GET /list_order/1126 HTTP/1.1" 200 25112
08/Jan/2024 19:11:57   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:57   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:58   INFO  "GET /list_order/1125 HTTP/1.1" 200 25160  None
INFO:django.server:"GET /list_order/1125 HTTP/1.1" 200 25160
08/Jan/2024 19:11:58   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:58   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:58   INFO  "GET /list_order/1124 HTTP/1.1" 200 25145  None
INFO:django.server:"GET /list_order/1124 HTTP/1.1" 200 25145
08/Jan/2024 19:11:58   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:58   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:59   INFO  "GET /list_order/1123 HTTP/1.1" 200 25136  None
INFO:django.server:"GET /list_order/1123 HTTP/1.1" 200 25136
08/Jan/2024 19:11:59   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:59   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:59   INFO  "GET /list_order/1122 HTTP/1.1" 200 25112  None
INFO:django.server:"GET /list_order/1122 HTTP/1.1" 200 25112
08/Jan/2024 19:11:59   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:11:59   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:00   INFO  "GET /list_order/1121 HTTP/1.1" 200 25128  None
INFO:django.server:"GET /list_order/1121 HTTP/1.1" 200 25128
08/Jan/2024 19:12:00   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:00   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:00   INFO  "GET /list_order/1120 HTTP/1.1" 200 25486  None
INFO:django.server:"GET /list_order/1120 HTTP/1.1" 200 25486
08/Jan/2024 19:12:00   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:00   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:00   INFO  "GET /list_order/1119 HTTP/1.1" 200 25097  None
INFO:django.server:"GET /list_order/1119 HTTP/1.1" 200 25097
08/Jan/2024 19:12:00   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:00   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:01   INFO  "GET /list_order/1118 HTTP/1.1" 200 25462  None
INFO:django.server:"GET /list_order/1118 HTTP/1.1" 200 25462
08/Jan/2024 19:12:01   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:01   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:01   INFO  "GET /list_order/1117 HTTP/1.1" 200 25092  None
INFO:django.server:"GET /list_order/1117 HTTP/1.1" 200 25092
08/Jan/2024 19:12:01   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:01   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:02   INFO  "GET /list_order/1114 HTTP/1.1" 200 25129  None
INFO:django.server:"GET /list_order/1114 HTTP/1.1" 200 25129
08/Jan/2024 19:12:02   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:02   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:02   INFO  "GET /list_order/1113 HTTP/1.1" 200 25151  None
INFO:django.server:"GET /list_order/1113 HTTP/1.1" 200 25151
08/Jan/2024 19:12:02   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:02   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:03   INFO  "GET /list_order/1112 HTTP/1.1" 200 24868  None
INFO:django.server:"GET /list_order/1112 HTTP/1.1" 200 24868
08/Jan/2024 19:12:03   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:03   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:03   INFO  "GET /list_order/1109 HTTP/1.1" 200 25099  None
INFO:django.server:"GET /list_order/1109 HTTP/1.1" 200 25099
08/Jan/2024 19:12:03   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:03   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:03   INFO  "GET /list_order/1108 HTTP/1.1" 200 25146  None
INFO:django.server:"GET /list_order/1108 HTTP/1.1" 200 25146
08/Jan/2024 19:12:04   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:04   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:04   INFO  "GET /list_order/1106 HTTP/1.1" 200 25183  None
INFO:django.server:"GET /list_order/1106 HTTP/1.1" 200 25183
08/Jan/2024 19:12:04   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:04   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:04   INFO  "GET /list_order/1100 HTTP/1.1" 200 25157  None
INFO:django.server:"GET /list_order/1100 HTTP/1.1" 200 25157
08/Jan/2024 19:12:04   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:04   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:05   INFO  "GET /list_order/1098 HTTP/1.1" 200 25141  None
INFO:django.server:"GET /list_order/1098 HTTP/1.1" 200 25141
08/Jan/2024 19:12:05   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:05   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:05   INFO  "GET /list_order/1097 HTTP/1.1" 200 25115  None
INFO:django.server:"GET /list_order/1097 HTTP/1.1" 200 25115
08/Jan/2024 19:12:05   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:05   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:06   INFO  "GET /list_order/1096 HTTP/1.1" 200 25178  None
INFO:django.server:"GET /list_order/1096 HTTP/1.1" 200 25178
08/Jan/2024 19:12:06   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:06   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:07   INFO  "GET /list_order/1097 HTTP/1.1" 200 25115  None
INFO:django.server:"GET /list_order/1097 HTTP/1.1" 200 25115
08/Jan/2024 19:12:07   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:12:07   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:20:55   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
08/Jan/2024 19:20:56   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 19:22:01   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.
08/Jan/2024 19:22:02   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 19:24:55   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.
08/Jan/2024 19:24:57   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 19:25:11   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 19:25:16   INFO  "GET /stat/ HTTP/1.1" 200 191899  None
INFO:django.server:"GET /stat/ HTTP/1.1" 200 191899
08/Jan/2024 19:25:16   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:25:16   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:28:08   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.
08/Jan/2024 19:28:10   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 19:29:34   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.
08/Jan/2024 19:29:35   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 19:29:38   INFO  "GET /stat/ HTTP/1.1" 200 191900  None
INFO:django.server:"GET /stat/ HTTP/1.1" 200 191900
08/Jan/2024 19:29:38   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 19:29:38   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 20:01:36   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.
08/Jan/2024 20:01:38   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 20:01:44   INFO  "GET /stat/ HTTP/1.1" 200 191898  None
INFO:django.server:"GET /stat/ HTTP/1.1" 200 191898
08/Jan/2024 20:01:44   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 20:01:44   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 20:01:47   INFO  "GET /stat/ HTTP/1.1" 200 191898  None
INFO:django.server:"GET /stat/ HTTP/1.1" 200 191898
08/Jan/2024 20:01:47   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 20:01:47   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 20:04:45   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
08/Jan/2024 20:04:47   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 20:07:30   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
08/Jan/2024 20:07:32   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 20:07:44   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
08/Jan/2024 20:07:46   INFO  Watching for file changes with StatReloader  None
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-01-08 20:07:47.095853
WARNING:root:ОШИБКА:        type object 'DataFromInvoice' has no attribute 'get_quantity_orders_by_type'
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/venv3/lib/python3.11/site-packages/django/views/generic/base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py", line 160, in get_context_data
    c = DataFromInvoice.get_quantity_orders_by_type(repairer=self.request.user)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'DataFromInvoice' has no attribute 'get_quantity_orders_by_type'

WARNING:root:============================================================
08/Jan/2024 20:07:47   WARNING  Bad Request: /stat/  None
WARNING:django.request:Bad Request: /stat/
08/Jan/2024 20:07:47   WARNING  "GET /stat/ HTTP/1.1" 400 133  None
WARNING:django.server:"GET /stat/ HTTP/1.1" 400 133
08/Jan/2024 20:08:06   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/views.py changed, reloading.
08/Jan/2024 20:08:08   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 20:08:11   INFO  "GET /stat/ HTTP/1.1" 200 191900  None
INFO:django.server:"GET /stat/ HTTP/1.1" 200 191900
08/Jan/2024 20:08:11   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 20:08:11   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 20:15:55   INFO  /home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.  None
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/sakhlis/web/app_site/repository.py changed, reloading.
08/Jan/2024 20:15:57   INFO  Watching for file changes with StatReloader  None
08/Jan/2024 20:15:59   INFO  "GET / HTTP/1.1" 200 43211  None
INFO:django.server:"GET / HTTP/1.1" 200 43211
08/Jan/2024 20:15:59   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 20:16:03   INFO  "GET /list_order HTTP/1.1" 200 53814  None
INFO:django.server:"GET /list_order HTTP/1.1" 200 53814
08/Jan/2024 20:16:03   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 20:16:06   INFO  "GET /user/51 HTTP/1.1" 200 16064  None
INFO:django.server:"GET /user/51 HTTP/1.1" 200 16064
08/Jan/2024 20:16:06   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
08/Jan/2024 20:16:09   INFO  "GET /stat/ HTTP/1.1" 200 191899  None
INFO:django.server:"GET /stat/ HTTP/1.1" 200 191899
08/Jan/2024 20:16:09   WARNING  "GET /static/js/counter.js HTTP/1.1" 404 1798  None
WARNING:django.server:"GET /static/js/counter.js HTTP/1.1" 404 1798
