WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/slippers/templatetags/slippers.py", line 102, in render
    template = context.template.engine.get_template(self.template_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist:  partials/form_for_order.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 89, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist:  partials/form_for_order.html
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/slippers/templatetags/slippers.py", line 102, in render
    template = context.template.engine.get_template(self.template_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist:  partials/form_for_order.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 89, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist:  partials/form_for_order.html
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/models.py changed, reloading.
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/models.py changed, reloading.
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /list_order
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: app_site_orderlist.apartment_id_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 89, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/defaulttags.py", line 194, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
    cursor.execute(sql, params)
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/debug_toolbar/panels/sql/tracking.py", line 246, in execute
    return self._record(super().execute, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/debug_toolbar/panels/sql/tracking.py", line 167, in _record
    return method(sql, params)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: app_site_orderlist.apartment_id_id
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/models.py changed, reloading.
WARNING:django.request:Not Found: /schema
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/admin.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/admin.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/admin.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/models.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/models.py changed, reloading.
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/forms.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/forms.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/forms.py changed, reloading.
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: account/register.html
ERROR:django.request:Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: account/register.html
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/forms.py changed, reloading.
ERROR:django.request:Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: account/register.html
ERROR:django.request:Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: account/register.html
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/forms.py changed, reloading.
ERROR:django.request:Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: account/register.html
ERROR:django.request:Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: account/register.html
ERROR:django.request:Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: account/register.html
ERROR:django.request:Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: account/register.html
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: account/register.html
ERROR:django.request:Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: account/register.html
ERROR:django.request:Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: account/register.html
ERROR:django.request:Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: account/register.html
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/forms.py changed, reloading.
ERROR:django.request:Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: account/register.html
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/forms.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/forms.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/forms.py changed, reloading.
ERROR:django.request:Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 89, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1070, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1047, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/utils/html.py", line 420, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
                                           ^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/boundfield.py", line 34, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/boundfield.py", line 107, in as_widget
    return widget.render(
           ^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/widgets.py", line 280, in render
    context = self.get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/widgets.py", line 693, in get_context
    context["widget"]["optgroups"] = self.optgroups(
                                     ^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/widgets.py", line 633, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
ERROR:django.request:Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 89, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1070, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1047, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/utils/html.py", line 420, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
                                           ^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/boundfield.py", line 34, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/boundfield.py", line 107, in as_widget
    return widget.render(
           ^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/widgets.py", line 280, in render
    context = self.get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/widgets.py", line 693, in get_context
    context["widget"]["optgroups"] = self.optgroups(
                                     ^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/widgets.py", line 633, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/forms.py changed, reloading.
ERROR:django.request:Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 89, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1070, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1047, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/utils/html.py", line 420, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
                                           ^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/boundfield.py", line 34, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/boundfield.py", line 107, in as_widget
    return widget.render(
           ^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/widgets.py", line 280, in render
    context = self.get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/widgets.py", line 693, in get_context
    context["widget"]["optgroups"] = self.optgroups(
                                     ^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/widgets.py", line 633, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
ERROR:django.request:Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 89, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1070, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1047, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/utils/html.py", line 420, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
                                           ^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/boundfield.py", line 34, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/boundfield.py", line 107, in as_widget
    return widget.render(
           ^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/widgets.py", line 280, in render
    context = self.get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/widgets.py", line 693, in get_context
    context["widget"]["optgroups"] = self.optgroups(
                                     ^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/widgets.py", line 633, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/forms.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/forms.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/forms.py changed, reloading.
ERROR:django.request:Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 89, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1070, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1047, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/utils/html.py", line 420, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
                                           ^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/boundfield.py", line 34, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/boundfield.py", line 107, in as_widget
    return widget.render(
           ^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/widgets.py", line 280, in render
    context = self.get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/widgets.py", line 693, in get_context
    context["widget"]["optgroups"] = self.optgroups(
                                     ^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/widgets.py", line 633, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
ERROR:django.request:Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 89, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1070, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/base.py", line 1047, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/utils/html.py", line 420, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
                                           ^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/boundfield.py", line 34, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/boundfield.py", line 107, in as_widget
    return widget.render(
           ^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/widgets.py", line 280, in render
    context = self.get_context(name, value, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/widgets.py", line 693, in get_context
    context["widget"]["optgroups"] = self.optgroups(
                                     ^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/widgets.py", line 633, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/forms.py changed, reloading.
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: account/register.html
ERROR:django.request:Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: account/register.html
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: account/register.html
ERROR:django.request:Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: account/register.html
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: /account/register.html
ERROR:django.request:Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: /account/register.html
ERROR:django.request:Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: /account/register.html
ERROR:django.request:Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: /account/register.html
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py changed, reloading.
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-03-30 12:16:11.549144
WARNING:root:ОШИБКА:        UserRegisterView.post() takes 1 positional argument but 2 were given
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: UserRegisterView.post() takes 1 positional argument but 2 were given

WARNING:root:============================================================
WARNING:django.request:Bad Request: /register/
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py changed, reloading.
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-03-30 12:17:03.965688
WARNING:root:ОШИБКА:        UserRegisterView.post() takes 1 positional argument but 2 were given
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: UserRegisterView.post() takes 1 positional argument but 2 were given

WARNING:root:============================================================
WARNING:django.request:Bad Request: /register/
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py changed, reloading.
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-03-30 12:17:40.596316
WARNING:root:ОШИБКА:        BaseCreateView.post() missing 1 required positional argument: 'request'
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py", line 34, in post
    b = super().post(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseCreateView.post() missing 1 required positional argument: 'request'

WARNING:root:============================================================
WARNING:django.request:Bad Request: /register/
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py changed, reloading.
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-03-30 12:18:56.190900
WARNING:root:ОШИБКА:        BaseCreateView.post() missing 1 required positional argument: 'request'
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py", line 34, in post
    b = super().post(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseCreateView.post() missing 1 required positional argument: 'request'

WARNING:root:============================================================
WARNING:django.request:Bad Request: /register/
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-03-30 12:19:02.942593
WARNING:root:ОШИБКА:        BaseCreateView.post() missing 1 required positional argument: 'request'
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py", line 34, in post
    b = super().post(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseCreateView.post() missing 1 required positional argument: 'request'

WARNING:root:============================================================
WARNING:django.request:Bad Request: /register/
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py changed, reloading.
WARNING:root:===========================================================
WARNING:root:ВРЕМЯ:     2024-03-30 12:19:42.938338
WARNING:root:ОШИБКА:        'WSGIRequest' object has no attribute 'get'
WARNING:root:ТРЭЙСБЭК:     Traceback (most recent call last):
  File "/home/alprostov/PycharmProjects/sakhlis/web/app_site/exeptions.py", line 35, in dispatch
    response = super().dispatch(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py", line 35, in post
    i=self.form_class(self.request).save(commit=False)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/contrib/auth/forms.py", line 140, in save
    user = super().save(commit=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/models.py", line 532, in save
    if self.errors:
       ^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/forms.py", line 433, in full_clean
    self._clean_fields()
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/forms.py", line 440, in _clean_fields
    value = bf.initial if field.disabled else bf.data
                                              ^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/boundfield.py", line 135, in data
    return self.form._widget_data_value(self.field.widget, self.html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/forms.py", line 220, in _widget_data_value
    return widget.value_from_datadict(self.data, self.files, html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alprostov/.local/share/virtualenvs/web-mek5ITq2/lib64/python3.11/site-packages/django/forms/widgets.py", line 297, in value_from_datadict
    return data.get(name)
           ^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'get'

WARNING:root:============================================================
WARNING:django.request:Bad Request: /register/
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py changed, reloading.
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/views.py changed, reloading.
INFO:django.utils.autoreload:/home/alprostov/PycharmProjects/sakhlis/web/app_site/exeptions.py changed, reloading.
